### PR TITLE
Single-file mirrors + configuration versioning + cleanups

### PR DESCRIPTION
**Pull request by mattmccutchen**
This is a single pull request for single-file mirrors (#64) and configuration versioning (#66), intended to be released as Braid 1.1.0 to give users a new feature in exchange for forcing them to run `braid upgrade-config`.

~~@realityforge, you can start to review this, but please **do not merge yet** because the version table web page still has to be written.~~

~~The tests that the upgraded `.braids.json` content equals the expected currently fail on Windows because `.braids.json` gets written with LF but the expected files get converted to CRLF by Git for Windows with the recommended settings.  I can just make the the comparisons ignore line endings or maybe use gitattributes to stop the CRLF conversion, but I wonder if we should solve the deeper problem by writing `.braids.json` in text mode.  That should also stop the warning spew from the test suite that files with LF committed on Windows will be checked back out with CRLF.  @realityforge, do you know why you wrote the file in binary mode in 9d3fa11?~~
For now I made the comparisons ignore line endings.  I filed #77.

### CODE REVIEW

**Comment by mattmccutchen** [comment]
I'm coming back to this pull request to try to get it out the door.  I emailed cristibalan on January 8, asking him to consider switching the GitHub Pages source to the master branch and transferring the repository to an organization, and he never responded.  However, we can proceed without his help by manually copying master to gh-pages every time we change the documentation.  We can leave #67 to track switching the GitHub Pages source to master.  And if we transfer the repository to an organization later, it should be straightforward to set up redirects from https://cristibalan.github.io/braid/ ; I've tested that process on my own GitHub Pages site.

I've made up my mind on the remaining to-do items, so @realityforge, I just need your review.  This pull request makes Braid print a link to https://cristibalan.github.io/braid/config_versions.html ; you can preview the page at https://mattmccutchen.github.io/braid/config_versions.html .  The pull request has passed the test suite on my Windows VM.

**Comment by realityforge** [comment]
Ok - I will have a look at it this weekend

**Comment by realityforge** [comment]
Ok - merged and released.

Thanks - for putting in the work to get this here ;)

**Comment by mattmccutchen** [comment]
Thanks.  As planned, I've manually copied the master branch to gh-pages (and renamed the old gh-pages to gh-pages.pre20180222, in case anyone cares about it).

**Pull request merged**
