### PR TITLE
Resolve .git/MERGE_MSG correctly when using a linked working tree.

### PR DESCRIPTION
**Pull request by mattmccutchen**
Tested manually that the "braid update" I was trying to perform now
works.

### CODE REVIEW

**Comment by realityforge** [comment]
Hi, Would you mind looking into the test failure? And possibly rebasing off master?

Thanks!

**Comment by mattmccutchen** [comment]
The test failure is fixed.  Thanks for letting me know.  (It doesn't look like there's a setting for GitHub to notify me when my pull request fails a check, and I didn't think to check manually.)

**Comment by realityforge** [comment]
Released as 1.0.15

**Comment by realityforge** [comment]
Thanks!

**Pull request merged**
