### PR TITLE
skip git-lfs smuge & filter-process during push operation

### PR DESCRIPTION
**Pull request by venatirr**
I tried to resolve an issue I had with braid push, because of Git LFS enabled on my repository.
Also I want to keep my global Git configuration, having git-lfs smuge & filter-process on

[filter "lfs"]
    clean = git-lfs clean -- %f
    smudge = git-lfs smudge -- %f
    process = git-lfs filter-process
    required = true
The error I got was like that:

$ git-lfs.exe filter-process
Error downloading object: fileName : Smudge error: Error downloading fileName: batch request: missing protocol: ""

### CODE REVIEW

**Comment by mattmccutchen** [comment]
Thanks for fixing the readme.

I'm probably going to spend more time learning about Git LFS regardless before I can approve this PR.  But if you want to help speed things along, can you provide full steps to reproduce the error?

**Comment by venatirr** [comment]
Sure, I'll add details how to reproduce it, hope in the first part of the next week.

**Comment by venatirr** [comment]
Hello,

Here are the steps to reproduce the issue I had with LFS files.

I've created an example repo, suppose I want to braid id into another repository - https://github.com/venatirr/braid-lfs-issues.git
Add this configuration to your global gitconfig file
[filter "lfs"]
	clean = git-lfs clean -- %f
	smudge = git-lfs smudge -- %f
	process = git-lfs filter-process
	required = true

Now braid the Src folder from the _braid-lfs-issues_ repo into your repository, do some changes (for example in main.txt file).
Then try to execute braid push --branch whatever name

You'll have to get this error:
Braid: Shell error: Downloading Chromedriver/chromedriver.exe (7.5 MB)

Thanks!

**Comment by mattmccutchen** [comment]
I finally made some time today to do some basic tests and gain a basic understanding of the issues involved here.  (I've been really busy for the past few months.)  Thanks venatirr for providing the steps to reproduce and for your patience.

I took the following steps:
1. Apply the global Git LFS configuration.
2. Create my own "superproject" repository.
3. `braid add https://github.com/venatirr/braid-lfs-issues.git`

In step (3), I got an error that the LFS objects couldn't be downloaded, which makes sense because without more help from Braid, LFS has no way to know that the objects should be downloaded from the central subproject repository (https://github.com/venatirr/braid-lfs-issues.git).  Since you said you got the error on `braid push`, I assume you must have bypassed the `braid add` error by turning off LFS in the superproject repository via the same `git config` settings that are in the PR.  When I did that, `braid add` succeeded, and then `braid push` gave me an error similar to yours.

It seems that no one has considered the interaction between Braid and Git LFS yet.  I can imagine how full integration would work: `braid add` and `braid update` would need to force the download of the LFS objects from the upstream subproject into the local superproject repository so they could be checked out, and from there, uploading them to the central superproject repository would work the same as adding any LFS file.  `braid push` would essentially reverse the process.  I certainly don't have the time right now to implement and test all of that, though if someone wanted to contribute an implementation, I'd be open to reviewing it.

So I guess our goal here is just to unblock your use case.  Am I right to infer that you don't need the subproject's LFS content to be accessible in the superproject and are willing to manually configure the superproject to turn off LFS, and you just need to overcome this problem where `braid push` of a change to a non-LFS file fails because the `braid push` temporary repository has a broken LFS configuration?  If so, this PR certainly achieves the goal, but it feels rather ad-hoc and I'd have to think more carefully about whether applying these configuration settings unconditionally is at least no worse than the status quo in all cases.  (Can we rule out that some other user is doing something else custom with Braid and LFS that would be broken by this change?)

So I'd like to propose a different change to Braid that I want to make regardless of LFS but that I think will also solve the LFS problem here: skip checking out the files in the working tree of the temporary repository, so the LFS filter is never invoked in the temporary repository.  I've prototyped this in #99.  With #99, when I follow the steps here, `braid push` gets as far as asking me to log in to GitHub, and I cancel because I don't have write permission on https://github.com/venatirr/braid-lfs-issues.git anyway.  I also ran Braid's existing test suite on my machine and everything passed, but I haven't written a new test for the change yet.

@venatirr, can you confirm whether #99 solves the problem you were seeing?  @venatirr and @realityforge: do you have opinions on the relative merits of the two approaches?

**Comment by realityforge** [comment]
@mattmccutchen I don't really understand it enough to judge the relative merits but what you are saying makes sense ... however "skip checking out the files in the working tree of the temporary repository" is something I would like to see regardless ;)

**Comment by realityforge** [comment]
I believe this has been addressed by @mattmccutchen and released as version `1.1.4`. 

Thanks for contributing! Sorry it took a while to get to it ;)

**Pull request closed without merging**
